name: Sync Assets to R2

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: auto

      - name: Install AWS CLI
        run: |
          aws --version

      - name: Upload to R2
        run: |
          aws s3 sync . s3://firefly-cdn \
            --exclude ".git/*" \
            --endpoint-url https://${{ secrets.CLOUDFLARE_ACCOUNT_ID }}.r2.cloudflarestorage.com
