name: Sync Assets to R2

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Get Changed Files
        id: changed
        run: |
          git diff --name-only HEAD^ HEAD > changed_files.txt

          echo "Changed files:"
          cat changed_files.txt

      - name: Upload Changed Files to R2
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
        run: |
          while IFS= read -r file; do

            # Skip deleted files
            if [ ! -f "$file" ]; then
              continue
            fi

            echo "Uploading $file"

            aws s3 cp "$file" "s3://firefly-cdn/$file" \
              --endpoint-url "https://${ACCOUNT_ID}.r2.cloudflarestorage.com"

          done < changed_files.txt
